version: '2'

services:
  app:
    image: flask_bs:latest
    working_dir: /app
    build: .
    ports:
      - "5000:5000"
  whoami:
    image: flask_bs:latest
    expose:
      - "5000"
    environment:
      - VIRTUAL_HOST=second.my
      - VIRTUAL_PORT=5000
